Update to child pipelines

diff --git a/Makefile.common b/Makefile.common
--- a/Makefile.common
+++ b/Makefile.common
@@ -3,27 +3,21 @@
 #############################
 # global settings
 #############################
+## These should really not be changed
 SHELL := /bin/bash
 EXTRAMAKEFLAGS += --warn-undefined-variables
 MAKEFLAGS += $(EXTRAMAKEFLAGS)
-.DEFAULT_GOAL: help
-
-#############################
-# environment detection
-#############################
-CENTOS7 := $(if $(findstring CentOS Linux release 7,$(shell cat /etc/centos-release 2>/dev/null)),1,0)
-ARMV7 := $(if $(findstring armv7l,$(shell /usr/bin/arch)),1,0)
-AARCH64 := $(if $(findstring aarch64,$(shell /usr/bin/arch)),1,0)
-ARM := $(if $(ARMV7),1,$(if $(AARCH64),1,0))
-UBUNTU24 := $(if $(findstring Ubuntu 24,$(shell lsb_release -a 2>/dev/null)),1,0)
-NUMPROC := $(shell grep -c ^processor /proc/cpuinfo)
 GITJ := 4
+IS_TOP := $(if $(filter $(TOP),$(CURDIR)),1,0)
+.DEFAULT_GOAL: help
 
 #############################
 # variable templates
 #############################
+## these are variables and functions that can be used line functions
 
 bsg_var_blank :=
+
 define bsg_var_newline
 
 $(bsg_var_blank)
@@ -40,38 +34,58 @@ define bsg_var_user
 		)
 endef
 
+define bsg_var_upper
+	$(shell echo $(1) | tr a-z A-z)
+endef
+
+define bsg_var_lower
+	$(shell echo $(1) | tr A-Z a-z)
+endef
+
 #############################
 # function templates
 #############################
-define bsg_fn_upper
-	$(eval $@_var := $(1))
-	$(shell echo $($@_var) | $(TR) a-z A-Z)
+
+define bsg_fn_info
+	$(eval $@_msg := $(1))
+	echo "BSG-INFO: ${$@_msg}"
 endef
 
-define bsg_fn_lower
-	$(eval $@_var := $(1))
-	$(shell echo $(1) | $(TR) A-Z a-z)
+define bsg_fn_warn
+	$(eval $@_msg := $(1))
+	echo "BSG-WARN: ${$@_msg}"
+endef
+
+define bsg_fn_error
+	$(eval $@_msg := $(1))
+	echo "BSG-ERROR: ${$@_msg}"
 endef
 
 define bsg_fn_mkhookdirs
 	$(eval $@_hookdirs := $(1))
 	$(eval $@_hookmatch := $(addsuffix /%,$($@_hookdirs)))
 	$(eval $@_uservars := $(call bsg_var_user))
-	$(eval $@_uppervars := $(filter $(call bsg_fn_upper,$($@_uservars)),$($@_uservars)))
+	$(eval $@_uppervars := $(filter $(call bsg_var_upper,$($@_uservars)),$($@_uservars)))
 	$(eval $@_uppervals := $(foreach var,$($@_uppervars),$($(var))))
-	$(eval $@_filtered := $(filter $($@_hookmatch),$($@_uppervals)))
-	mkdir -p $($@_hookdirs) $($@_filtered)
+	$(eval $@_extradirs := $(filter $($@_hookmatch),$($@_uppervals)))
+	$(call bsg_fn_info,"hookdirs: ${$@_hookdirs}")
+	mkdir -p ${$@_hookdirs} && ls ${$@_hookdirs} || :
+	$(call bsg_fn_info,"extradirs: ${$@_extradirs}");
+	mkdir -p ${$@_extradirs} && ls ${$@_extradirs} || :
 endef
 
 define bsg_fn_checkout_submodules
-	$(eval $@_submodules := $(1))
-	for t in ${$@_submodules}; do \
-		d=$$($(ECHO) $$t | $(CUT) -d '@' -f 1); \
-		s=$$($(ECHO) $$t | $(CUT) -d '@' -f 2); \
-		echo "Disabling checkout for $$d/$$s"; \
-		git -C $$d config --local submodule.$$s.update none; \
-	done
-	git submodule update --init --recursive --recommend-shallow --progress .
+	$(eval $@_hooks := $(1))
+	git submodule foreach --recursive 'git config --unset submodule.$$name.update || :'
+	git submodule foreach --recursive " \
+		key=\$$toplevel@\$$sm_path; \
+		case ' ${$@_hooks} ' in \
+			*' '\$$key' '*) \
+				echo \"skipping \$$key\";; \
+			*) \
+				git -C \$$toplevel submodule update --init --recursive --jobs=$(GITJ) \$$sm_path;; \
+		esac \
+	"
 endef
 
 define bsg_fn_default_configure
@@ -80,12 +94,14 @@ define bsg_fn_default_configure
 	$(eval $@_prefix := $(3))
 	$(eval $@_extra := $(4))
 	$(eval $@_strip := -s -Wl,--gc-sections)
-	cd ${$@_src}; $(AUTOCONF) -o ./configure || true; \
+	$(call bsg_info,attempting autoconf)
+	cd ${$@_src}; autoconf -o ./configure || :
+	$(call bsg_info,attempting configure)
 	cd ${$@_work}; \
 		CFLAGS="$(CFLAGS)" \
 		CXXFLAGS="$(CXXFLAGS)" \
 		LDFLAGS="${$@_strip} $(LDFLAGS)" \
-		${$@_src}/configure --srcdir=${$@_src} --prefix=${$@_prefix} ${$@_extra}
+		${$@_src}/configure --srcdir=${$@_src} --prefix=${$@_prefix} ${$@_extra} || :
 endef
 
 define bsg_fn_default_cmake
@@ -94,7 +110,7 @@ define bsg_fn_default_cmake
 	$(eval $@_prefix := $(3))
 	$(eval $@_extra := $(4))
 	$(eval $@_strip := -s -Wl,--gc-sections)
-	$(CMAKE) -B ${$@_work} -S ${$@_src} -DCMAKE_INSTALL_PREFIX=${$@_prefix} \
+	cmake -B ${$@_work} -S ${$@_src} -DCMAKE_INSTALL_PREFIX=${$@_prefix} \
 		-DCMAKE_BUILD_TYPE=Release \
 		-DCMAKE_C_FLAGS="$(CFLAGS)" \
 		-DCMAKE_CXX_FLAGS="$(CXXFLAGS)" \
@@ -103,36 +119,19 @@ endef
 
 define bsg_fn_strip_binaries
 	$(eval $@_install := $(1))
-	$(FIND) $($@_install) -type f -exec sh -c '\
+	find ${$@_install} -type f -exec sh -c '\
 		for file; do \
-			if $(FILE) "$$file" | $(GREP) -qE "ELF (.* )?(executable|shared)"; then \
-				$(STRIP) "$$file" >/dev/null 2>&1 || true; \
+			if file "$$file" | grep -qE "ELF (.* )?(executable|shared)"; then \
+				strip "$$file" >/dev/null 2>&1 || :; \
 			fi; \
 	done \
 	' sh {} +
 endef
 
-define bsg_fn_info
-	$(eval $@_msg = $(1))
-	$(eval $@_prefix = "BSG-INFO: ")
-	echo "$($@_prefix) $($@_msg)"
-endef
-
-define bsg_fn_warn
-	$(eval $@_msg = $(1))
-	$(eval $@_prefix = "BSG-WARN: ")
-	echo "$($@_prefix) $($@_msg)"
-endef
-
-define bsg_fn_error
-	$(eval $@_msg = $(1))
-	$(eval $@_prefix = "BSG-ERROR: ")
-	echo "$($@_prefix) $($@_msg)"
-endef
-
 #############################
 # target templates
 #############################
+## these can be implemented as $(eval $(call statements))
 
 define bsg_tgt_build_tag
 	$(eval MAKEFLAGS := $(filter-out $(EXTRAMAKEFLAGS),$(MAKEFLAGS)))
@@ -155,8 +154,8 @@ $(patch_target): | $(patch_tag)
 $(repatch_target):
 	@rm -f $(touch_dir)/$(name).patch.*
 	@if [ -f $(src_dir)/.git ]; then \
+		git submodule update --quiet --init --force $(src_dir); \
 		git -C $(src_dir) clean -fdx; \
-		git -C $(src_dir) reset --hard; \
 		git -C $(src_dir) submodule foreach 'git clean -fdx; git reset --hard'; \
 	fi
 	@+$(MAKE) $(patch_tag)
@@ -174,7 +173,7 @@ $(patch_tag):
 	)
 	@touch $$@
 $(build_target): | $(build_tag)
-$(rebuild_target):
+$(rebuild_target): $(repatch_target)
 	@rm -rf $(touch_dir)/$(name).build.*
 	@rm -rf  $(work_dir)/$(name)
 	@+$(MAKE) $(build_tag)
@@ -202,11 +201,11 @@ endef
 .PHONY: help
 help: ## prints this target
 	@$(eval HELPFILTER := $(if $(findstring $(CURDIR),$(TOP)),xxxxxxxx,checkout|bleach_all))
-	@$(GREP) -h '\s##\s' $(MAKEFILE_LIST) \
-		| $(GREP) -Ev "$(HELPFILTER)" \
-		| $(AWK) 'BEGIN {FS = ":.*?## "}; {printf "\033[36m  %-30s\033[0m %s\n", $$1, $$2}'
+	@grep -h '\s##\s' $(MAKEFILE_LIST) \
+		| grep -Ev "$(HELPFILTER)" \
+		| awk 'BEGIN {FS = ":.*?## "}; {printf "\033[36m  %-30s\033[0m %s\n", $$1, $$2}'
 
-ifeq ($(CURDIR),$(TOP))
+ifeq ($(IS_TOP),1)
 # Global reset
 .PHONY: bleach_all
 bleach_all: ## wipes the whole repo clean: use with caution
@@ -215,6 +214,7 @@ bleach_all: ## wipes the whole repo clean: use with caution
 
 # Global checkout
 .PHONY: checkout
+checkout: $(BSG_CADENV_DIR)
 checkout: ## checkout submodules
 	@$(call bsg_fn_mkhookdirs,$(HOOK_CHECKOUT_DIRS))
 	@git -C "$(TOP)" submodule update --init --jobs=$(GITJ)
@@ -224,12 +224,19 @@ endif
 ##########################################################
 ## Cad environment
 ##########################################################
+## override if needed
+## BSG members should use bsg_cadenv, which _should_ be automatically handled by this script
+CENTOS7  ?= $(if $(findstring CentOS Linux release 7,$(shell cat /etc/centos-release 2>/dev/null)),1,0)
+ARMV7    ?= $(if $(findstring armv7l,$(shell /usr/bin/arch)),1,0)
+AARCH64  ?= $(if $(findstring aarch64,$(shell /usr/bin/arch)),1,0)
+ARM      ?= $(if $(ARMV7),1,$(if $(AARCH64),1,0))
+UBUNTU24 ?= $(if $(findstring Ubuntu 24,$(shell lsb_release -a 2>/dev/null)),1,0)
+NUMPROC  ?= $(shell grep -c ^processor /proc/cpuinfo)
 
-## Override CAD tool paths if needed
 CMAKE     ?= $(if $(shell which cmake3),cmake3,cmake)
 DC_SHELL  ?= dc_shell
 DOCKER    ?= docker
-_DVE      ?= dve
+DVE       ?= dve
 GCC       ?= gcc
 GXX       ?= g++
 GTKWAVE   ?= gtkwave
@@ -241,14 +248,15 @@ VCS       ?= vcs
 VERILATOR ?= verilator
 VIVADO    ?= vivado
 YOSYS     ?= yosys
-## Specify license path if needed
+# Specify license paths if needed
 VCS_HOME        ?=
 LM_LICENSE_FILE ?=
+# Commonly needed on CentOS
+export VCS_ARCH_OVERRIDE=linux
 
-ifneq ($(MAKECMDGOALS),help)
+ifneq (,$(filter-out bleach_all help ,$(MAKECMDGOALS)))
 BSG_CADENV_DIR ?= $(TOP)/bsg_cadenv
 include $(BSG_CADENV_DIR)/cadenv.mk
-ifeq ($(CURDIR),$(TOP))
 %/cadenv.mk:
 	# BSG users leverage a machine-specific cadenv
 	#   Here, we add sourcing to get these variables as well
@@ -265,9 +273,8 @@ ifeq ($(CURDIR),$(TOP))
 	fi
 	@echo "Successfully built $@!"
 endif
-endif
 
 # Saves initial values so that we can filter them later
-# MUST BE BEFORE THE PROJECT VARIABLES
+# MUST BE LAST
 VARS_OLD := $(.VARIABLES)
 
