hotfix: checkout macros

diff --git a/Makefile.common b/Makefile.common
--- a/Makefile.common
+++ b/Makefile.common
@@ -1,3 +1,4 @@
+# v1.0
 
 #############################
 # global settings
@@ -16,52 +17,7 @@ AARCH64 := $(if $(findstring aarch64,$(shell /usr/bin/arch)),1,0)
 ARM := $(if $(ARMV7),1,$(if $(AARCH64),1,0))
 UBUNTU24 := $(if $(findstring Ubuntu 24,$(shell lsb_release -a 2>/dev/null)),1,0)
 NUMPROC := $(shell grep -c ^processor /proc/cpuinfo)
-
-##########################################################
-## basic tools
-##########################################################
-AUTORECONF ?= autoreconf
-AUTOCONF   ?= autoconf
-AWK        ?= awk
-BASENAME   ?= basename
-CAT        ?= cat
-CMAKE      ?= $(if $(shell which cmake3),cmake3,cmake)
-CD         ?= cd
-CP         ?= cp
-CURL       ?= curl
-CUT        ?= cut
-DIFF       ?= diff
-DOCKER     ?= docker
-ECHO       ?= echo
-ENVSUBST   ?= envsubst
-EXIT       ?= exit
-FILE       ?= file
-FIND       ?= find
-GCC        ?= gcc
-GIT        ?= git
-GIT_APPLY  ?= $(GIT) apply --ignore-whitespace --ignore-space-change
-GIT_CHECK  ?= $(GIT_APPLY) --check --reverse
-GREP       ?= grep
-MKDIR      ?= mkdir
-MKDIRP     ?= mkdir -p
-MV         ?= mv
-PRINTF     ?= printf
-PYTHON     ?= $(if $(shell which python3),python3,python)
-RM         ?= rm
-RMRF       ?= rm -rf
-SED        ?= sed
-STTY       ?= stty
-STRIP      ?= strip
-SYMLINK    ?= ln -nsf
-TAIL       ?= tail
-TAR        ?= tar
-TEE        ?= tee
-TEST       ?= test
-TOUCH      ?= touch
-TR         ?= tr
-WCOUNT     ?= wc -l
-WGET       ?= wget
-XXD        ?= xxd
+GITJ := 4
 
 #############################
 # variable templates
@@ -89,12 +45,12 @@ endef
 #############################
 define bsg_fn_upper
 	$(eval $@_var := $(1))
-	$(shell $(ECHO) $($@_var) | $(TR) a-z A-Z)
+	$(shell echo $($@_var) | $(TR) a-z A-Z)
 endef
 
 define bsg_fn_lower
 	$(eval $@_var := $(1))
-	$(shell $(ECHO) $(1) | $(TR) A-Z a-z)
+	$(shell echo $(1) | $(TR) A-Z a-z)
 endef
 
 define bsg_fn_mkhookdirs
@@ -104,18 +60,18 @@ define bsg_fn_mkhookdirs
 	$(eval $@_uppervars := $(filter $(call bsg_fn_upper,$($@_uservars)),$($@_uservars)))
 	$(eval $@_uppervals := $(foreach var,$($@_uppervars),$($(var))))
 	$(eval $@_filtered := $(filter $($@_hookmatch),$($@_uppervals)))
-	$(shell $(MKDIRP) $($@_hookdirs) $($@_filtered))
+	mkdir -p $($@_hookdirs) $($@_filtered)
 endef
 
-define bsg_fn_disable_submodules
+define bsg_fn_checkout_submodules
 	$(eval $@_submodules := $(1))
 	for t in ${$@_submodules}; do \
-	    d=$$($(ECHO) $$t | $(CUT) -d '@' -f 1); \
-	    s=$$($(ECHO) $$t | $(CUT) -d '@' -f 2); \
-	    $(ECHO) "Disabling checkout for $$d/$$s"; \
-	    $(GIT) -C $$d config --local submodule.$$s.update none; \
-	    $(GIT) -C $$d submodule sync --recursive; \
+		d=$$($(ECHO) $$t | $(CUT) -d '@' -f 1); \
+		s=$$($(ECHO) $$t | $(CUT) -d '@' -f 2); \
+		echo "Disabling checkout for $$d/$$s"; \
+		git -C $$d config --local submodule.$$s.update none; \
 	done
+	git submodule update --init --recursive --recommend-shallow --progress .
 endef
 
 define bsg_fn_default_configure
@@ -124,12 +80,12 @@ define bsg_fn_default_configure
 	$(eval $@_prefix := $(3))
 	$(eval $@_extra := $(4))
 	$(eval $@_strip := -s -Wl,--gc-sections)
-	$(CD) ${$@_src}; $(AUTOCONF) -o ./configure || true; \
-	$(CD) ${$@_work}; \
-	    CFLAGS="$(CFLAGS)" \
-	    CXXFLAGS="$(CXXFLAGS)" \
-	    LDFLAGS="${$@_strip} $(LDFLAGS)" \
-	    ${$@_src}/configure --srcdir=${$@_src} --prefix=${$@_prefix} ${$@_extra}
+	cd ${$@_src}; $(AUTOCONF) -o ./configure || true; \
+	cd ${$@_work}; \
+		CFLAGS="$(CFLAGS)" \
+		CXXFLAGS="$(CXXFLAGS)" \
+		LDFLAGS="${$@_strip} $(LDFLAGS)" \
+		${$@_src}/configure --srcdir=${$@_src} --prefix=${$@_prefix} ${$@_extra}
 endef
 
 define bsg_fn_default_cmake
@@ -139,10 +95,10 @@ define bsg_fn_default_cmake
 	$(eval $@_extra := $(4))
 	$(eval $@_strip := -s -Wl,--gc-sections)
 	$(CMAKE) -B ${$@_work} -S ${$@_src} -DCMAKE_INSTALL_PREFIX=${$@_prefix} \
-	    -DCMAKE_BUILD_TYPE=Release \
-	    -DCMAKE_C_FLAGS="$(CFLAGS)" \
-	    -DCMAKE_CXX_FLAGS="$(CXXFLAGS)" \
-	    -DCMAKE_EXE_LINKER_FLAGS="${$@_strip} $(LDFLAGS)"
+		-DCMAKE_BUILD_TYPE=Release \
+		-DCMAKE_C_FLAGS="$(CFLAGS)" \
+		-DCMAKE_CXX_FLAGS="$(CXXFLAGS)" \
+		-DCMAKE_EXE_LINKER_FLAGS="${$@_strip} $(LDFLAGS)"
 endef
 
 define bsg_fn_strip_binaries
@@ -159,19 +115,19 @@ endef
 define bsg_fn_info
 	$(eval $@_msg = $(1))
 	$(eval $@_prefix = "BSG-INFO: ")
-	$(ECHO) "$($@_prefix) $($@_msg)"
+	echo "$($@_prefix) $($@_msg)"
 endef
 
 define bsg_fn_warn
 	$(eval $@_msg = $(1))
 	$(eval $@_prefix = "BSG-WARN: ")
-	$(ECHO) "$($@_prefix) $($@_msg)"
+	echo "$($@_prefix) $($@_msg)"
 endef
 
 define bsg_fn_error
 	$(eval $@_msg = $(1))
 	$(eval $@_prefix = "BSG-ERROR: ")
-	$(ECHO) "$($@_prefix) $($@_msg)"
+	echo "$($@_prefix) $($@_msg)"
 endef
 
 #############################
@@ -197,41 +153,35 @@ define bsg_tgt_build_tag
 	$(eval internal_target := $(work_dir)/$(name)/.$(name)_build)
 $(patch_target): | $(patch_tag)
 $(repatch_target):
-	@$(RM) -f $(touch_dir)/$(name).patch.*
+	@rm -f $(touch_dir)/$(name).patch.*
 	@if [ -f $(src_dir)/.git ]; then \
-		$(GIT) submodule deinit -f $(src_dir); \
-		$(GIT) submodule init $(src_dir); \
-		$(GIT) submodule update $(src_dir); \
+		git -C $(src_dir) clean -fdx; \
+		git -C $(src_dir) reset --hard; \
+		git -C $(src_dir) submodule foreach 'git clean -fdx; git reset --hard'; \
 	fi
 	@+$(MAKE) $(patch_tag)
 $(patch_tag):
 	@$(eval patch_root := $(patch_dir)/$(if $(src_dir),$(shell $(BASENAME) $(src_dir)),$(name)))
 	@$(eval patch_files := $(shell $(FIND) $(patch_root) -name "*.patch" 2>/dev/null))
-	@if [ -f $(src_dir)/.git ]; then \
-		$(ECHO) "Synchronizing submodules for $(name)"; \
-		$(GIT) -C $(src_dir) submodule sync --recursive; \
-		$(ECHO) "Checking out submodules for $(name)"; \
-		$(GIT) -C $(src_dir) submodule update --init --recursive; \
-	fi
 	# For some reason the bash for loop doesn't work here
-	@$(ECHO) "Applying patches $(patch_files)"
+	@echo "Applying patches $(patch_files)"
 	@$(foreach p,$(patch_files),\
-		$(GIT_APPLY) $(p) --directory $(dir $(subst $(patch_dir)/,,$(p)));\
+		git apply --ignore-whitespace --ignore-space-change $(p) --directory $(dir $(subst $(patch_dir)/,,$(p)));\
 	)
-	@$(ECHO) "Checking patches $(patch_files)"
+	@echo "Checking patches $(patch_files)"
 	@$(foreach p,$(patch_files),\
-		$(GIT_CHECK) $(p) --directory $(dir $(subst $(patch_dir)/,,$(p)));\
+		git apply --ignore-whitespace --ignore-space-change --check --reverse  $(p) --directory $(dir $(subst $(patch_dir)/,,$(p)));\
 	)
-	@$(TOUCH) $$@
+	@touch $$@
 $(build_target): | $(build_tag)
 $(rebuild_target):
-	@$(RMRF) $(touch_dir)/$(name).build.*
-	@$(RMRF)  $(work_dir)/$(name)
+	@rm -rf $(touch_dir)/$(name).build.*
+	@rm -rf  $(work_dir)/$(name)
 	@+$(MAKE) $(build_tag)
 $(build_tag): | $(patch_tag)
-	@$(MKDIRP) $(work_dir)/$(name)
+	@mkdir -p $(work_dir)/$(name)
 	@+$(MAKE) $(internal_target)
-	@$(TOUCH) $$@
+	@touch $$@
 $(internal_target): $(src_dir)
 endef
 
@@ -241,7 +191,7 @@ define bsg_tgt_build_submodule
 	$(eval touch_dir := $(3))
 	$(eval patch_dir := $(4))
 	$(eval work_dir := $(5))
-	$(eval tag := $(if $(src_dir),$(shell $(CD) $(src_dir); $(GIT) rev-parse HEAD),any))
+	$(eval tag := $(if $(src_dir),$(shell cd $(src_dir); git rev-parse HEAD),any))
 	$(eval $(call bsg_tgt_build_tag,$(name),$(src_dir),$(touch_dir),$(patch_dir),$(work_dir),$(tag)))
 endef
 
@@ -260,20 +210,15 @@ ifeq ($(CURDIR),$(TOP))
 # Global reset
 .PHONY: bleach_all
 bleach_all: ## wipes the whole repo clean: use with caution
-	@$(GIT) -C "$(git rev-parse --show-toplevel)" submodule deinit -f .
-	@$(GIT) -C "$(git rev-parse --show-toplevel)" clean -ffdx
+	@git -C "$(TOP)" submodule deinit -f .
+	@git -C "$(TOP)" clean -ffdx
 
 # Global checkout
 .PHONY: checkout
 checkout: ## checkout submodules
 	@$(call bsg_fn_mkhookdirs,$(HOOK_CHECKOUT_DIRS))
-	# Synchronize any pending updates
-	@$(GIT) submodule sync
-	@$(GIT) submodule init
-	# Disable long checkouts
-	@$(call bsg_fn_disable_submodules,$(HOOK_DISABLE_SUBMODULES))
-	# Do the checkout
-	@$(GIT) submodule update
+	@git -C "$(TOP)" submodule update --init --jobs=$(GITJ)
+	@$(call bsg_fn_checkout_submodules,$(HOOK_DISABLE_SUBMODULES))
 endif
 
 ##########################################################
@@ -281,13 +226,20 @@ endif
 ##########################################################
 
 ## Override CAD tool paths if needed
-VCS       ?= vcs
-URG       ?= urg
-VERILATOR ?= verilator
+CMAKE     ?= $(if $(shell which cmake3),cmake3,cmake)
 DC_SHELL  ?= dc_shell
-VIVADO    ?= vivado
+DOCKER    ?= docker
 _DVE      ?= dve
+GCC       ?= gcc
+GXX       ?= g++
 GTKWAVE   ?= gtkwave
+PYTHON    ?= $(if $(shell which python3),python3,python)
+SURELOG   ?= surelog
+SURFER    ?= surfer
+URG       ?= urg
+VCS       ?= vcs
+VERILATOR ?= verilator
+VIVADO    ?= vivado
 YOSYS     ?= yosys
 ## Specify license path if needed
 VCS_HOME        ?=
@@ -303,15 +255,15 @@ ifeq ($(CURDIR),$(TOP))
 	@$(eval export CADENV_URL := git@github.com:bespoke-silicon-group/bsg_cadenv)
 	# Recursive make to include the new fragment
 	@if [ -f "$(BSG_CADENV_DIR)/cadenv.mk" ]; then \
-		$(ECHO) "bsg_cadenv already exists"; \
+		echo "bsg_cadenv already exists"; \
 	elif [[ ! -z $$(git ls-remote --exit-code $${CADENV_URL} HEAD 2> /dev/null) ]]; then \
-		$(GIT) clone --recurse-submodules $${CADENV_URL} $(@D); \
+		git clone --recurse-submodules $${CADENV_URL} $(@D); \
 	else \
-		$(ECHO) "bsg_cadenv not found"; \
-		$(MKDIRP) $(@D); \
-		$(TOUCH) $@; \
+		echo "bsg_cadenv not found"; \
+		mkdir -p $(@D); \
+		touch $@; \
 	fi
-	@$(ECHO) "Successfully built $@!"
+	@echo "Successfully built $@!"
 endif
 endif
 
